/**
 * default number of decimals on formatted numbers
 */
const DEFAULT_NUMBER_FORMAT_DECIMALS = 2;

/**
 * unit conversion from decimal to integer
 */
const DEFAULT_CONVERSION_VALUE_DECIMAL_INTEGER = 100;

/**
 * disciplina id
 */
const SPORT_ID = {
  CALCIO: 1,
  BASKET: 2,
  TENNIS: 3,
  VOLLEY: 5,
  HOCKEY: 6,
  TENNIS_TAVOLO: 60,
};

/***
 *
 * Sport Home
 *
 */

const NUMBER_HOME_CDE_VIEW = 3;

/**
 * SELL
 */

const SELL_STATUS = {
  NOT_SELLING: "-1",
  OK: "1024",
};

const SELL_ERROR_CODE = {
  GENERIC_ERROR: "100",
  NOT_FOUND: "404",
  ODDS_CHANGED: "20102",
  UNDER_ACCEPTANCE: "20888",
  UNDER_ACCEPTANCE_REJECETED: "20888_REJECTED",
  UNDER_ACCEPTANCE_TIMEOUT: "20888_TIMEOUT",
  UNDER_ACCEPTANCE_AMOUNTS_CHANGED: "20888_AMOUNTS_CHANGED",
};

const ACCEPTANCE_STATUS = {
  REJECTED: "REJECTED",
  TIMEOUT: "TIMEOUT",
  OK_AMOUNTS_CHANGED: "OK_AMOUNTS_CHANGED",
};
/**
 * LIVESCORE
 */

/**
 * status codes
 */
const MATCH_STATUS_ONGOING = 1;

/**
 * set-based livescore server
 */

const SET_BASED_LIVESCORE_FIRST_SERVER = "FIRST";
const SET_BASED_LIVESCORE_SECOND_SERVER = "SECOND";

/**
 * advantage for Tennis
 */
const SET_BASED_LIVESCORE_ADVANTAGE_POINTS = 50;

/**
 * current game for set-based livescore
 */
const SET_BASED_LIVESCORE_CURRENT_GAME = "PeriodGame";

/**
 *  livescore current score
 */
const CURRENT_SCORE = "Current";

/**
 * livescore cards
 */
const LIVESCORE_CARD_TYPE = {
  PLAY: "PLAY",
  YELLOW_CARD: "YELLOW_CARD",
  SECOND_YELLOW_CARD: "SECOND_YELLOW_CARD",
  RED_CARD: "RED_CARD",
};

/**
 *
 */
const TEAM1_ID = 1;
const TEAM2_ID = 2;

/**
 * livescore timer_based render interval
 */
const LIVESCORE_TIMER_BASED_RENDER_INTERVAL = 5;

/**
 * Not available outcome status
 */
const NOT_AVAILABLE_OUTCOMES_STATUS = {
  NOTANY: "NOTANY",
  SOME: "SOME",
  ALL: "ALL",
};

/**
 * numpad paga_voucher
 */

const NUMPAD_PAGA_VOUCHER = ["A", "B", "C", "D", "E", "F", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"];
/**
 * error code SALDO CASSA INSUFFICIENTE VOUCHER
 */

const SALDO_CASSA_ERROR_VOUCHER_ID = "SALDO_CASSA_INSUFFICIENTE";
/**
 * error code VOUCHER SCADUTO O BLOCCATO
 */

const VOUCHER_EXPIRED_BLOCKED = "20002";

const HIGHER_LIMIT_VOUCHER = 500;
const LOWER_LIMIT_VOUCHER = 1;

/**
 * Number customer service page login
 */
const NUNBER_CUSTOMER_SERVICE = "848.88.55.44";

/**
 * Value response not logged fetch currentUser
 */
const RESPONSE_FETCH = {
  CURRENT_USER_NOT_LOGGED: "USER NOT LOGGED IN",
  LOGIN_USER_LOGGED_IN: "USER LOGGED IN",
};

/**
 * Browser router paths
 */
const BROWSER_ROUTER_PATH_MAP = {
  HOME: "/",
  LOGIN: "/login",
};

/**
 * Negative sign Borderò
 */

const NEGATIVE_ELEMENT_BORDERO = [
  "COMMON_CANCEL",
  "COMMON_PAYMENT",
  "GLOBAL_REFUND",
  "COMMON_REFUND",
  "COMMON_PAYMENT_REFUND",
  "VOUCHER_USAGE",
  "VOUCHER_PAYMENT",
  "GAME_ACCOUNT_WITHDRAWAL",
];

/**
 * Codicescommesse per ragruppamenti virtual
 */
const CODICE_SCOMMESSA_VIRTUAL = {
  CALCIO_DOPPIA_CHANCE_IN: 11,
  CALCIO_DOPPIA_CHANCE_OUT: 12,
  CALCIO_DOPPIA_CHANCE_IN_OUT: 13,
  CALCIO_UNDER_OVER_1_5: 19,
  CALCIO_UNDER_OVER_2_5: 14,

  CALCIO_PRO_DOPPIA_CHANCE_IN: 1011,
  CALCIO_PRO_DOPPIA_CHANCE_OUT: 1012,
  CALCIO_PRO_DOPPIA_CHANCE_IN_OUT: 1013,
  CALCIO_PRO_UNDER_OVER_1_5: 1019,
  CALCIO_PRO_UNDER_OVER_2_5: 1014,

  CALCIO_ULTRA_DOPPIA_CHANCE_IN: 175,
  CALCIO_ULTRA_DOPPIA_CHANCE_OUT: 176,
  CALCIO_ULTRA_DOPPIA_CHANCE_IN_OUT: 177,
  CALCIO_ULTRA_UNDER_OVER_1_5: 178,
  CALCIO_ULTRA_UNDER_OVER_2_5: 179,

  MATCHDAY_ULTRA_DOPPIA_CHANCE_IN: 175,
  MATCHDAY_ULTRA_DOPPIA_CHANCE_OUT: 176,
  MATCHDAY_ULTRA_DOPPIA_CHANCE_IN_OUT: 177,
  MATCHDAY_ULTRA_UNDER_OVER_1_5: 178,
  MATCHDAY_ULTRA_UNDER_OVER_2_5: 179,

  FOOTBALL_DOPPIA_CHANCE_IN: 210,
  FOOTBALL_DOPPIA_CHANCE_OUT: 211,
  FOOTBALL_DOPPIA_CHANCE_IN_OUT: 212,
  FOOTBALL_UNDER_OVER_1_5: 201,
  FOOTBALL_UNDER_OVER_2_5: 202,
  FOOTBALL_UNDER_OVER_3_5: 203,

  RIGORE_UNDER_OVER_5_5: 190,
};

/**
 * Codicescommesse virtual race
 */
const CODICE_SCOMMESSA_VIRTUAL_RACE = {
  VINCENTE: 1,
  PIAZZATO_2: 2,
  PIAZZATO_3: 3,
  PIAZZATO_4: 4,
  ACCOPPIATA_IN_ORDINE: 5,
  ACCOPPIATA_NON_IN_ORDINE: 18,
  TRIO_IN_ORDINE: 6,
  TRIO_NON_IN_ORDINE: 7,

  BIGLIE_VINCENTE: 21,
  BIGLIE_PIAZZATO_2: 22,
  BIGLIE_PIAZZATO_3: 26,
  BIGLIE_ACCOPPIATA_IN_ORDINE: 29,
  BIGLIE_ACCOPPIATA_NON_IN_ORDINE: 27,
  BIGLIE_TRIO_IN_ORDINE: 30,
  BIGLIE_TRIO_NON_IN_ORDINE: 28,

  VINCENTE_PIAZZATO: 999,
  ACCOPPIATA_TRIO: 666,
};
/**
 * Codicescommesse accoppiata trio provaider + id scommessa
 */
const CODICE_SCOMMESSA_ACCOPPIATA_TRIO = {
  ACCOPPIATA_IN_ORDINE: ["18_5", "18_29", "31_4"],
  ACCOPPIATA_NON_IN_ORDINE: ["18_18", "18_27", "31_5"],
  TRIO_IN_ORDINE: ["18_6", "18_30", "31_6", "31_30"],
  TRIO_NON_IN_ORDINE: ["18_7", "18_28", "31_7", "31_28"],
};
/**
 * Codicescommesse calcio risultato esatto a gruppi
 */
const CODICE_SCOMMESSA_RISULTATO_ESATTO_GRUPPI = {
  CALCIO: 25,
  CALCIO_ULTRA: 183,
  CALCIO_PRO: 1025,
  RIGORI: 189,
};

/**
 * Codice disciplina  'provaider'_'idDisciplina'
 */
const CODICE_DISCIPLINA_VIRTUAL = {
  IPPICA: "18_1",
  CANI: "18_2",
  AUTOMOBILISMO: "18_4",
  CALCIO: "18_5",
  CICLISMO: "18_7",
  CALCIO_PRO: "18_9",
  CALCIO_ULTRA: "18_12",
  BIGLIE: "18_13",
  RIGORI: "18_23",
  MATCH_DAY: "18_24",
  CAVALLI_DELUXE: "31_1",
  CANI_DELUXE: "31_2",
  FOOTBAL_ALL_STARS: "31_5",
  FOOTBAL_ALL_STARS_LEAGUE: "31_6",
};

const DISANONIMADOCUMENTTYPE = {
  CARTA_IDENTITA: "CARTA IDENTITA",
  PATENTE: "PATENTE",
  PASSAPORTO: "PASSAPORTO",
};

const DISANONIMAGENDEROPTION = {
  MASCHIO: "M",
  FEMMINA: "F",
};

const BOOKING_PROVENANCE = {
  SELFY: 2,
  PRENOTATORE: 8,
  SISAL_IT: 3,
  SITO_MOBILE_APP_MP: 9,
  // GAMING_TERMINAL: 5, //precompilata
};

const configuration = {
  SELL_STATUS,
  SELL_ERROR_CODE,
  ACCEPTANCE_STATUS,
  DEFAULT_NUMBER_FORMAT_DECIMALS,
  DEFAULT_CONVERSION_VALUE_DECIMAL_INTEGER,
  SPORT_ID,
  MATCH_STATUS_ONGOING,
  SET_BASED_LIVESCORE_ADVANTAGE_POINTS,
  SET_BASED_LIVESCORE_FIRST_SERVER,
  SET_BASED_LIVESCORE_SECOND_SERVER,
  SET_BASED_LIVESCORE_CURRENT_GAME,
  CURRENT_SCORE,
  LIVESCORE_CARD_TYPE,
  TEAM1_ID,
  TEAM2_ID,
  LIVESCORE_TIMER_BASED_RENDER_INTERVAL,
  NOT_AVAILABLE_OUTCOMES_STATUS,
  NUMPAD_PAGA_VOUCHER,
  HIGHER_LIMIT_VOUCHER,
  LOWER_LIMIT_VOUCHER,
  SALDO_CASSA_ERROR_VOUCHER_ID,
  VOUCHER_EXPIRED_BLOCKED,
  NUNBER_CUSTOMER_SERVICE,
  RESPONSE_FETCH,
  BROWSER_ROUTER_PATH_MAP,
  NEGATIVE_ELEMENT_BORDERO,
  NUMBER_HOME_CDE_VIEW,
  CODICE_SCOMMESSA_VIRTUAL,
  CODICE_DISCIPLINA_VIRTUAL,
  CODICE_SCOMMESSA_VIRTUAL_RACE,
  CODICE_SCOMMESSA_ACCOPPIATA_TRIO,
  CODICE_SCOMMESSA_RISULTATO_ESATTO_GRUPPI,
  DISANONIMADOCUMENTTYPE,
  DISANONIMAGENDEROPTION,
  BOOKING_PROVENANCE,
};
export default configuration;
